### ISSUE TITLE
Question about: why Attentive context  is different from Implementation

### ISSUE THREAD

**Issue by hoaileba** [Wendy-Xiao/Extsumm_local_global_context#10]
Hi Wendy,
I just noticed the formula for calculating attention context in your research paper and the implementation is a bit different
In the paper, I see the score calculation formula is
![image](https://user-images.githubusercontent.com/56421735/183291220-68989368-526e-42de-ac6f-b89b3a38a25b.png)
but in your implementation, I see something like this
        local_context_representation = torch.stack(local_context_representation,0)
        local_context_representation = torch.bmm(section_indicator,local_context_representation)
        local_context_representation = local_context_representation.permute(1,0,2)
        local_context_representation = self.dropout_layer(local_context_representation)
        output = self.dropout_layer(output)
        context = torch.stack((local_context_representation,doc_represent),2)
        attn_in = torch.cat((context,output.unsqueeze(2).expand(-1,-1,2,-1)),3)
        attn_in = torch.tanh(attn_in)
according to the paper, before applying tanh you can multiply by a weight vector W but in the implementation, I don't see this. Am I doing something wrong here? Can you help explain this? Thank you so much

**Comment by Wendy-Xiao** [comment]
Hi there,

I think it was a typo in the paper on the order of tanh and the linear layer, you can find right in the next line that there is a linear layer 'feat_attn' applied to attn_in.
