### ISSUE TITLE
Questions about fields and labels in the data example given

### ISSUE THREAD

**Issue by CoderBinGe** [Wendy-Xiao/Extsumm_local_global_context#5]
**Looking forward to your reply, thank you！**
1. For **example-input.json**: what does field **section_lengths** mean? Indicates the number of sentences in each section or something else?
2. For **example-label.json**: As shown below, the label 1 here means that the fifth sentence of the article is a summary or something else?
![image](https://user-images.githubusercontent.com/26380524/143418100-06416aad-43d0-4349-8d9d-75e95fc71ce4.png)
3. For **example-abstract.txt**: This file is a summary of the article, right?

**Comment by Wendy-Xiao** [comment]
Hi, thanks for your interest in my work!

1. Yes, section_length means how many sentences are in this section.
2. Yes, 1 means the sentence should be selected to form the summary, and 0 means not. Specifically, all the sentences with '1's form the oracle summary.
3. Yes.

**Comment by CoderBinGe** [comment]
Ok, Thanks!
